# Generated by Django 4.2.6 on 2023-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_remove_carservice_updated_at_alter_carservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
