# Generated by Django 4.2.6 on 2023-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_carservice_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
