# Generated by Django 4.2.6 on 2023-11-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0005_remove_carservice_car_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='service_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carservice',
            name='techinician_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='carservice',
            name='techinician_phone',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
