# Generated by Django 4.2.6 on 2023-11-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0007_parttoservice_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='service_date',
            field=models.DateField(default=None),
        ),
    ]
