# Generated by Django 4.2.6 on 2023-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0008_alter_carservice_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttoservice',
            name='id_order',
            field=models.IntegerField(default=1),
        ),
    ]
