# Generated by Django 4.2.6 on 2023-11-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0009_parttoservice_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
