# Generated by Django 4.2.6 on 2023-11-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technician', '0012_alter_parttoservice_confirmed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttoservice',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='parttoservice',
            name='validated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='validated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
