# Generated by Django 4.2.6 on 2023-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0013_remove_parttoservice_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttoservice',
            name='validated_by',
            field=models.CharField(max_length=30),
        ),
    ]
