# Generated by Django 4.2.6 on 2023-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0014_alter_parttoservice_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttoservice',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
