# Generated by Django 4.2.6 on 2023-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0015_alter_parttoservice_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttoservice',
            name='car_video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
