# Generated by Django 4.2.6 on 2024-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0016_parttoservice_car_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='kilometer',
            field=models.IntegerField(default=0),
        ),
    ]
