# Generated by Django 4.2.6 on 2023-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
    ]
