# Generated by Django 4.2.6 on 2023-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermanage_is_staff_member_usermanage_is_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='is_owner_car',
            field=models.BooleanField(default=False),
        ),
    ]
