# Generated by Django 4.2.6 on 2023-11-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usermanage_is_owner_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanage',
            old_name='is_owner_car',
            new_name='is_owner',
        ),
    ]
